# Generated by Django 5.0.4 on 2024-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangaGen', '0005_protein_delete_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_accession', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('source_database', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('source_organism_taxId', models.CharField(max_length=50)),
                ('source_organism_scientificName', models.CharField(max_length=255)),
                ('source_organism_fullName', models.CharField(max_length=255)),
                ('gene', models.CharField(max_length=100)),
                ('in_alphafold', models.BooleanField()),
                ('entries_accession', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('dc_status', models.CharField(max_length=20)),
                ('representative', models.BooleanField()),
                ('model', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('protein_length', models.IntegerField()),
                ('entry_source_database', models.CharField(max_length=50)),
                ('entry_type', models.CharField(max_length=50)),
                ('entry_integrated', models.CharField(max_length=50)),
                ('sequence', models.TextField()),
            ],
        ),
    ]
